README.md
Updated the upgrade information link to point to the wiki page as a fix
for: https://github.com/opendatakit/opendatakit/issues/1296
=> Fix #1296 - upgrade information link broken

src/main/java/org/opendatakit/aggregate/client/popups/AuditCSVPopup.java, src/main/java/org/opendatakit/aggregate/client/submission/SubmissionService.java, src/main/java/org/opendatakit/aggregate/client/submission/SubmissionServiceAsync.java, src/main/java/org/opendatakit/aggregate/client/table/AuditCSVPopupClickHandler.java, src/main/java/org/opendatakit/aggregate/client/table/SubmissionTable.java, src/main/java/org/opendatakit/aggregate/server/SubmissionServiceImpl.java
This PR solves #102 
It covers just a basic feature to enable users to see Audit CSV contents inside a simple popup. 
Some UI improvements that could be addressed:
- New button image (currently using preview button image)
- Some styling or HTML structuring to the Audit CSV data (maybe formatting it into a table)
Some code improvements that could also be addressed:
- Reduce duplication of code in `SubmissionServiceImpl` and `BinaryDataServlet`
=> New feature that lets a user see Audit CSV contents inside a popup in Aggregate's submissions table

docs/intellij_setup.md
Use gradle wrapper to prevent path problems and make text match the screenshot
=> Use gradle wrapper, make text match screenshot

src/main/java/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java
Use classnames newly exposed from JavaRosa, rather than maintaining this list of classnames here as well as in JavaRosa (and in Collect).
Depends on https://github.com/dcbriccetti/javarosa/commit/15a825805a3f5976a908d0e8a1b65c7f8642cf96 .
@mitchellsundt, how does this look?
I can’t yet build and test Aggregate. I wonder if one of you who can could test this?
=> Remove duplicate lists of classes used for JavaRosa serialization

bitrock-installer/conf_variants/common/security.properties, bitrock-installer/files/legacyremoval/WEB-INF/appengine-web.xml, functionalTest/resources/Integration.properties, src/main/resources/security.properties
Closes #136.
In places where there are usernames, I replaced `msundt` with `administrator`. In places without usernames, I used `example` and `example.org`.
This is a find/replace PR without any verification, but the only risk I can think of is that some platforms, somehow, may not allow `administrator`. That seems unlikely because I have used `administrator` for installs on GAE and Tomcat.
=> Replace msundt with administrator or example

src/main/java/org/opendatakit/aggregate/constants/ErrorConsts.java, src/main/java/org/opendatakit/aggregate/form/Form.java, src/main/java/org/opendatakit/aggregate/form/FormDefinition.java, src/main/java/org/opendatakit/aggregate/form/FormFactory.java, src/main/java/org/opendatakit/aggregate/form/IForm.java, src/main/java/org/opendatakit/aggregate/server/FormServiceImpl.java, src/main/java/org/opendatakit/common/persistence/CommonFieldsBase.java
Add new controls to prevent constant refresh of the UI due to unhandled exceptions server-side
Add log traces that give more information about these unhandled exceptions
Add github issues link in POSSIBLE_CORRUPTION error text
Closes #114
Comes from #127
=> Prevent refresh hell on identified cases of data corruption

src/main/java/org/opendatakit/aggregate/submission/SubmissionSet.java, src/main/java/org/opendatakit/aggregate/submission/type/RepeatSubmissionType.java, src/main/resources/security.properties
Closes #134
This PR solves a problem I introduced in a wrong rebase in PR #141 
Warning the user about missing/dupes in repeat tables would be handled in #135 
To test this PR, you can use these forms: 
- Normal repeat [Untitled Form.xml.tar.gz](https://github.com/opendatakit/aggregate/files/1476411/Untitled.Form.xml.tar.gz)
- Nested repeat [nested-repeats.xml.tar.gz](https://github.com/opendatakit/aggregate/files/1499968/nested-repeats.xml.tar.gz)
Just send a submission and alter the database to produce missing rows and duped rows. This example has a dupe row for `_ORDINAL_NUMBER` 1 and has no row for `_ORDINAL_NUMBER` 2.
_URI | _CREATOR_URI_USER | _CREATION_DATE | _LAST_UPDATE_URI_USER | _LAST_UPDATE_DATE | _PARENT_AURI | _ORDINAL_NUMBER | _TOP_LEVEL_AURI | SOME_TEXT
-- | -- | -- | -- | …
=> Solve (partially) dupes/missing rows/wrong sequences in repeat tables

.gitignore, build.gradle
Closes #169 
Confirmed that logs are written to the project folder and not the #HOME folder. Also confirmed that logs folder is not committed.
We could have used  http://akhikhl.github.io/gretty-doc/Logging.html to have a configure file, but this seems like the correct default behavior. Others can override if necessary.
I'm hoping that this doesn't override some logs in the application itself. I did not verify, but I don't think so though.
=> No gretty logs in $HOME

.circleci/config.yml, README.md
Closes #128
I tried the build on my CircleCI account and successfully got a build. 
We've used the Git LFS install technique on other ODK repos. The splitting up of the commands is silly, but I found it more reliable than the many attempts at setting correct values for `_JAVA_OPTS` and `GRADLE_OPTS`
Nope.
=> Enable Git LFS and fix broken build

installer/gae.zip
Closes #113
This PR updates the GAE Updater application's JAR file that will get embedded inside the Aggregate installer. The new version will run on Java8 and Java9 (since it's generated with the changes from [the corresponding PR on aggregate-components project](https://github.com/opendatakit/aggregate-components/pull/2)
Generated an installer and manually tested that
1. The installer can launch automatically the updater app
2. The updater app runs on Java8 and Java9 (tested by running it manually from the installation dir)
N/A 
None
No
=> Update the GAE Updater application's JAR

.circleci/config.yml, db/test/postgresql/init.sql
Closes #188 
I've run this on my branch and the tests run, but one test (org.opendatakit.common.persistence.QueryResultTest) fails, so the build fails. 
I've used default variables (e.g., circleci) that are the default so there is less "code" in the config. I used full switches for readability. The file location for the init.sql was done to match #181. Maybe it should be at root level?
Yes, this breaks the build. And because the build is broken, I'm cannot guarantee `.gradlew war` will actually produce a war. I bet it will though. Another risk is that I've grouped the gradle commands and we may run into memory problems. A final risk is that the test output is enormous and it makes loading the log in CircleCI annoying. Maybe we can silence that?
=> Enable testing on CircleCI

docs/installer-generation.md
With last PRs, I normalized task names to follow the same schema of `contextAction` like `gaeUpdate`, or `packerBuild`. 
I had to change the installer tasks and I forgot to update the docs (and tell anyone about this, sorry!)
Run changed tasks on my computer
N/A
None
Nope
=> Fix installer generation docs with updated gradle task name

buildSrc/src/main/groovy/org/opendatakit/aggregate/gradle/gae/Rollback.groovy, buildSrc/src/main/groovy/org/opendatakit/aggregate/gradle/gae/Update.groovy, gae.gradle, installer.gradle
Closes #227 
Closes #228
- Build the installer 
- Run the installer with Java 8 (8u161-oracle) and Java 9 (9.0.4-oracle)
- Deploy with `gradlew gaeUpdate`
- Installer size (linux x64) is 157MB
- `du -h`  on install location reports 298MB, 145MB of them by the AppEngine SDK
This is the quickest fix that feels safe
Nope
Nope
=> 1.5.0 release fixes

src/main/java/org/opendatakit/aggregate/client/OdkTablesManageInstanceFilesSubTab.java, src/main/java/org/opendatakit/aggregate/client/OdkTablesManageTableFilesSubTab.java, src/main/java/org/opendatakit/aggregate/client/OdkTablesViewTableSubTab.java, src/main/java/org/opendatakit/aggregate/client/popups/AuditCSVPopup.java, src/main/java/org/opendatakit/aggregate/client/popups/ChangePasswordPopup.java, src/main/java/org/opendatakit/aggregate/client/popups/ConfirmExportDeletePopup.java, src/main/java/org/opendatakit/aggregate/client/popups/ConfirmFormDeletePopup.java, src/main/java/org/opendatakit/aggregate/client/popups/ConfirmPublishDeletePopup.java, src/main/java/org/opendatakit/aggregate/client/popups/ConfirmPurgePopup.java, src/main/java/org/opendatakit/aggregate/client/popups/ConfirmPurgeUpToDatePopup.java, src/main/java/org/opendatakit/aggregate/client/popups/ConfirmUserDeletePopup.java, src/main/java/org/opendatakit/aggregate/client/popups/ExportPopup.java, src/main/java/org/opendatakit/aggregate/client/popups/FilterPopup.java, src/main/java/org/opendatakit/aggregate/client/popups/HelpBalloon.java, src/main/java/org/opendatakit/aggregate/client/popups/HelpBookPopup.java, src/main/java/org/opendatakit/aggregate/client/popups/KmlGeoPointSettingsSelectionRow.java, src/main/java/org/opendatakit/aggregate/client/popups/KmlGeoTraceNShapeSelectionRow.java, src/main/java/org/opendatakit/aggregate/client/popups/KmlOptionsPopup.java, src/main/java/org/opendatakit/aggregate/client/popups/PublishPopup.java, src/main/java/org/opendatakit/aggregate/client/popups/PurgeUpToDatePopup.java, src/main/java/org/opendatakit/aggregate/client/popups/VisualizationPopup.java, src/main/java/org/opendatakit/aggregate/client/table/ExportTable.java, src/main/java/org/opendatakit/aggregate/client/table/FormTable.java, src/main/java/org/opendatakit/aggregate/client/table/OdkAdminListTable.java, src/main/java/org/opendatakit/aggregate/client/table/OdkTablesTableList.java, src/main/java/org/opendatakit/aggregate/client/table/OdkTablesViewTable.java, src/main/java/org/opendatakit/aggregate/client/table/PublishTable.java, src/main/java/org/opendatakit/aggregate/client/table/SubmissionPaginationNavBar.java, src/main/java/org/opendatakit/aggregate/client/widgets/AggregateCheckBox.java, src/main/java/org/opendatakit/aggregate/client/widgets/PurgeButton.java
This PR changes some unsafe uses of HTML and html-capable GWT widgets using SafeHtml instances to ensure dynamic strings are properly escaped.
(GitHub detects changes on whole files for some reason... ignoring whitespaces while reviewing is recommended)
Manually browsed Aggregate screens.
This is just what the GWT recommends when dealing with dynamic html content.
Nope.
N/A
Nope.
=> Fix unsafe html strings

src/main/java/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java
Closes #255 
Uploaded a form and then uploaded the same form with its version changed. 
Verified that the new form gets stored in Aggregate.
Although it's not pretty to parse each XML doc twice, we have no other alternative (yet) because once JR returns a FormDef is too late already and we can't rely on extending the parser as on previous versions of JR.
Nope.
I used this one for my tests: [simple-form.xml.txt](https://github.com/opendatakit/aggregate/files/2095418/simple-form.xml.txt)
Nope.
=> Issue 255 Fix NPE when uploading a new form version

src/main/java/org/opendatakit/aggregate/client/table/PublishTable.java
Links HTML was being escaped. Now the links are shown correctly
Created a new Publish and verified that the links were clickable and worked as expected
It's a straightforward change.
Nope.
No
No
=> Fix the links on the form submissions publish table

installer/ear.zip, src/main/gae_ear/background/WEB-INF/appengine-web.xml, src/main/gae_ear/default/WEB-INF/appengine-web.xml
Closes #265 
We were experiencing an issue described [here](https://cloud.google.com/appengine/docs/standard/java/config/appref#url-stream-handler) after updating the engine to Java8
Updated a failing instance with this PR's version and verified that now it can publish again.
Conf changed according to official docs
Nope.
Nope.
Nope, although we have created [docs issue #753](https://github.com/opendatakit/docs/issues/753) to update installation instructions
=> Issue 265 fix for free google accounts

src/main/java/org/opendatakit/aggregate/client/table/ExportTable.java
Closes #259
Exported a form and verified that the link was being shown correctly and it worked.
This is a straightforward fix to acknowledge that the output of `ExportSummary.getResultFile()` is a safe HTML constant.
Nope.
No. Any form will work.
No.
=> Issue 259 Fix export list links

src/main/java/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java
Closes #266
This PR fixes a bug introduced in #256 by avoiding to interact over the root Document object, which would produce a class cast exception behind the reported issue
Uploaded the form attached to the issue without errors.
It's a narrow fix. It's kind of ugly, mainly because `Element.getParent()` can return another `Element` or the root `Document`, which makes everything harder. Using the parent `Node` class won't help either because it doesn't have everything we need. `Node` works well while inspecting descendants but is quite limited for inspecting ancestors.
Nope.
[the one in the issue](https://github.com/opendatakit/aggregate/files/2137652/odk_length.xml.txt)
Nope.
=> Issue 266 Fix the way we construct the nodeset definition of a binding

installer/gae.zip
Closes #264
This PR updates the JAR of the GAE updater used by the installer.
The new updater JAR is 40px wider on Linux hosts.
Launch the updater on Ubuntu and verify that now the button doesn't get cropped.
It's a straightforward change that only affects linux hosts.
Nope.
Nope.
Nope.
=> Issue 264 Use new version of GAE updater

src/main/java/org/opendatakit/aggregate/client/table/PublishTable.java
Closes #281 
Created a new publisher and verified that clicking on the link opens a new tab
It's a straightforward change that adds `target="_blank"` to the link
Nope.
Nope.
Nope.
=> Open JSON server links in a new tab

docs/vm-generation.md
Closes #232
This PR adds a docs file explaining how to build the VM with Packer using Gradle tasks. It also explains some details about some features of the VM.
No code change in this PR
N/A
N/A
N/A
N/A
=> Issue 232 Add Packer build instructions doc

.circleci/config.yml
Addresses #296
Visual inspection.
I like auto-updating to the latest minor release because that's what we expect from our users. It also feels like it gives us early warning of potential problems we'll run into when we upgrade to a major release.
=> Use latest minor release in CircleCI

src/main/java/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java
Closes #293
This PR changes the upload form process:
- When Aggregate detects that the form is encrypted, it tricks itself into thinking that the user sent the form defined in `BaseFormParserForJavaRosa.ENCRYPTED_FORM_DEFINITION` which defined field sizes of 2048
- This PR fixes this part of the process to take into account those sizing definitions
- Uploaded [this form](https://github.com/opendatakit/aggregate/files/2270898/encrypted-form.zip)
and verified with PostgreSQL that the `BASE64_ENCRYPTED_KEY` and `BASE64_ENCRYPTED_ELEMENT_SIGNATURE` fields have a size of 2048 chars
- Uploaded some submissions with Collect
- Pulled the form with Briefcase
- Exported the form with Briefcase
This is the narrowest/quickest patch I came up with reusing what we're already doing with non-encrypted …
=> Issue 293 Aggregate sets a wrong size for encryption fields

packer/aggregate.json
Tried a packer build and made sure it went to completion
This is for a hotfix and it only affects the packer build.
Nope. Checksums all match!
=> Debian puts latest release in release, so we must use archive instead

src/main/java/org/opendatakit/aggregate/servlet/ServiceAccountPrivateKeyUploadServlet.java
Closes #261
This PR adds a note telling users to reload page after changing the Google Simple API key. This will reload the maps javascript library, which 
- Used the master version to push the All Widgets form with some submissions
- Verified that the map was showing the watermarks
- Set the Google API keys
- Verified that the new note was shown
- Hit F5 to reload the page
- Verified that now the map was showing no watermarks
I considered forcing a programmatic reload of the page, but the way the form with the Google is sent prevents to do so without complicated JS code and HTML hacking.
Nope.
All Widgets with some submissions will do.
[Widgets.zip](https://github.com/opendatakit/aggregate/files/2305380/Widgets.zip)
No.
=> Issue 261 Visualize submissions on Map issue

src/main/java/org/opendatakit/aggregate/servlet/SubmissionDownloadListServlet.java
Closes #305
This PR adds an optional argument that can be added when downloading the list of a form's submissions to include incomplete submissions.
The new argument is `includeIncomplete` and accepts any value that can be parsed as `Boolean` i.e. `true`, and `false.
- With a form that had 73 submissions:
- Made 10 submissions incomplete by changing their `_IS_COMPLETE` field in the database
- Used Briefcase (version from PR https://github.com/opendatakit/briefcase/pull/615) to pull the form without the `--include_incomplete` flag. Verified that I got 63 submissions, as expected
- Clean the storage dir and pull again the form, this time adding the `--include_incomplete` flag. Verified that I got 73 submissions, as expected
This is the narrowest change I could come up with. No other …
=> Issue 305 add param to include incomplete subs

build.gradle, src/main/java/org/opendatakit/aggregate/client/form/FormAdminService.java, src/main/java/org/opendatakit/aggregate/client/permissions/AccessConfigurationSheet.java, src/main/java/org/opendatakit/aggregate/client/popups/ConfirmFormDeletePopup.java, src/main/java/org/opendatakit/aggregate/client/popups/ConfirmPurgePopup.java, src/main/java/org/opendatakit/aggregate/client/popups/ConfirmPurgeUpToDatePopup.java, src/main/java/org/opendatakit/aggregate/client/popups/ConfirmSubmissionDeletePopup.java, src/main/java/org/opendatakit/aggregate/client/security/SecurityUtils.java, src/main/java/org/opendatakit/aggregate/server/FormAdminServiceImpl.java, src/main/java/org/opendatakit/common/security/client/security/admin/SecurityAdminService.java, src/main/java/org/opendatakit/common/security/server/SecurityAdminServiceImpl.java, src/main/webapp/WEB-INF/web.xml
This PR adds extra security protections to some RPC calls:
- Change users from Site Admin > Edit Users
- Delete a form
- Delete submission
- Purge published data
- Purge submissions
First, I've manually verified that all these operations still work in my local Aggregate instance
Second, I've inspected the network interchange of the delete form action and I've resent it using curl from the command line to verify that it won't work since the CSRF token wasn't valid anymore.
This solution implements the [official instructions](http://www.gwtproject.org/doc/latest/DevGuideSecurityRpcXsrf.html) to add CSRF protection to GWT apps.
To reduce code duplication and complexity, I've created a wrapper that handles client-side CSRF requests.
Any third party hitting these RPCs will have to request a …
=> Security fixes

src/main/java/org/opendatakit/aggregate/client/externalserv/ServicesAdminService.java, src/main/java/org/opendatakit/aggregate/client/externalserv/ServicesAdminServiceAsync.java, src/main/java/org/opendatakit/aggregate/client/form/FormService.java, src/main/java/org/opendatakit/aggregate/client/form/FormServiceAsync.java, src/main/java/org/opendatakit/aggregate/client/popups/ExportPopup.java, src/main/java/org/opendatakit/aggregate/client/popups/KmlOptionsPopup.java, src/main/java/org/opendatakit/aggregate/client/popups/PublishPopup.java, src/main/java/org/opendatakit/aggregate/client/widgets/RestartButton.java, src/main/java/org/opendatakit/aggregate/server/FormServiceImpl.java, src/main/java/org/opendatakit/aggregate/server/ServicesAdminServiceImpl.java
This PR adds extra security protections to some RPC calls:
- Export submissions to CSV, JSON, and KML
- Create publishers: Fusion Table, Google Spreadsheet, RedCap Server, SimpleJSON Server, Ohmage Server
- Delete publisher
- Update Publisher API key and restart
~This PR is developed on top of #303 and it starts after commit e3035b0~
(the branch has been rebased after merging #303 into master)
First, I've manually verified that all these operations still work in my local Aggregate instance
Second, I've inspected the network interchange of the delete form action and I've resent it using curl from the command line to verify that it won't work since the CSRF token wasn't valid anymore.
This solution implements the [official instructions](http://www.gwtproject.org/doc/latest/DevGuideSecurityRp …
=> Security fixes batch 2

docs/build-and-run-a-virtual-machine.md, packer/ansible/roles/aggregate/files/aggregate-config.sh, packer/ansible/roles/aggregate/files/aggregate-report-ips.sh, packer/ansible/roles/tomcat/files/server.xml, packer/ansible/roles/tomcat/files/server.xml.original, packer/ansible/roles/tomcat/tasks/main.yml
Closes #312
This PR improves the `aggregate-config` tool that we ship in the Aggregate VM:
- Added a new `--net-mode` argument that will accept either `nat` or `bridge` values to adapt Tomcat's and Aggregate's configuration to the current VM network device mode.
This PR also simplifies the shell command to get the IP addresses on the VM for the MOTD.
Run the commands in the VM, having changed back and forth the network device. Verified that Aggregate was reachable in both nat and bridge scenarios.
No other approaches considered for this change. 
Nope.
No.
https://github.com/opendatakit/docs/issues/866
=> Issue 312 fix aggregate config

installer/gae.zip
Closes #320
Run the new JAR independently to check if works.
Build an installer and used it to update my GAE instance, which uses the new JAR (including deleting the token, getting the token, etc.)
N/A
None
Nope
No
=> Issue 320 Update the GAE Updater JAR file

src/main/java/org/opendatakit/aggregate/client/externalserv/ServicesAdminService.java, src/main/java/org/opendatakit/aggregate/client/externalserv/ServicesAdminServiceAsync.java, src/main/java/org/opendatakit/aggregate/client/form/FormAdminService.java, src/main/java/org/opendatakit/aggregate/client/form/FormAdminServiceAsync.java, src/main/java/org/opendatakit/aggregate/client/form/FormService.java, src/main/java/org/opendatakit/aggregate/client/form/FormServiceAsync.java, src/main/java/org/opendatakit/aggregate/client/popups/ChangeAppNamePopup.java, src/main/java/org/opendatakit/aggregate/client/popups/ConfirmExportDeletePopup.java, src/main/java/org/opendatakit/aggregate/client/popups/ConfirmPublishDeletePopup.java, src/main/java/org/opendatakit/aggregate/client/preferences/PreferenceService.java, src/main/java/org/opendatakit/aggregate/client/widgets/AcceptSubmissionCheckBox.java, src/main/java/org/opendatakit/aggregate/client/widgets/DisableFasterBackgroundActionsCheckbox.java, src/main/java/org/opendatakit/aggregate/client/widgets/DownloadableCheckBox.java, src/main/java/org/opendatakit/aggregate/client/widgets/EnableOdkTablesCheckbox.java, src/main/java/org/opendatakit/aggregate/client/widgets/MarkSubmissionCompleteButton.java, src/main/java/org/opendatakit/aggregate/client/widgets/SkipMalformedSubmissionsCheckbox.java
This PR adds extra security protections to some RPC calls:
- Enable accept submissions on form
- Mark submission as complete 
- Enable downloading a form
- Delete exported form
- Delete publisher
- Enable ODK Tables 
- Set ODK App name
- Set skip malformed Submissions
This a follow up on #303 and #308
See #303 and #308
Any third party hitting these RPCs will have to request a CSRF token before making them. 
No.
No.
=> Security fixes batch 3

src/main/java/org/opendatakit/aggregate/constants/common/ExternalServiceType.java
Address #290
Ran the app and confirmed the publish dropdown is there in Submissions tab. Also confirmed that publisher types in Published Data showed up.
I did not try this with an install with an existing publisher so it'd be good to test that users that upgrade won't be harmed.
Just a targeted text change.
There might be people who use the text of this drop down to do things, but given that these publishers don't work, it's unlikely.
Not yet. After we deprecate in v2.0 then we should update the docs.
=> Warn users of upcoming deprecation

src/main/java/org/opendatakit/aggregate/client/ExportSubTab.java, src/main/java/org/opendatakit/aggregate/client/FiltersDataPanel.java, src/main/java/org/opendatakit/aggregate/client/FormsSubTab.java, src/main/java/org/opendatakit/aggregate/client/LayoutUtils.java, src/main/java/org/opendatakit/aggregate/client/PermissionsSubTab.java, src/main/java/org/opendatakit/aggregate/client/PreferencesSubTab.java, src/main/java/org/opendatakit/aggregate/client/PublishSubTab.java, src/main/java/org/opendatakit/aggregate/client/SubmissionAdminSubTab.java
This PR attempts to give users a heads up about the availability of a newer Aggregate version.
A new note will appear on the Filters tab at the bottom left indicating the current version and a link if there's a newer version available. Otherwise, it tells the user that they're "up to date".
Run on my dev server and verified that both messages where correctly being shown.
It's a very narrow implementation, trying to have minimal impact on the layout
It's, by the way, the most cross-browser, backwards-compatible JS code I've written in my life:
```js
var req = new XMLHttpRequest();
req.open('GET', 'https://api.github.com/repos/opendatakit/aggregate/releases/latest', false);
req.send(null);
if (req.readyState === 4 && req.status === 200)
return JSON.parse(req.responseText).tag_name;
``` …
=> Add note warning about a new Aggregate version

build.gradle
This PR bumps the JavaRosa dependency to 2.12.1-SNAPSHOT, which includes a hotfix to support dynamic `randomize()` seeds.
=> Bump JR version to 2.12.1

src/main/java/org/opendatakit/aggregate/submission/type/jr/JRDateType.java, src/main/java/org/opendatakit/aggregate/submission/type/jr/JRTemporal.java
Closes #346
This
Manually tested with a form uploaded with Aggregate v1.x, and then loaded with this PR (v2.x)
Format dates with ISO_LOCAL_DATE formater to avoid non-parseable values
- ISO_DATE will output `2018-01-01+01:00` if there's time zone info, which we won't be able to parse with LocalDate.parse()
Nope.
Any form with a date field will do.
Nope.
=> Format dates with ISO_LOCAL_DATE formatter to avoid non-parseable values

src/main/java/org/opendatakit/aggregate/client/permissions/AccessConfigurationSheet.java, src/main/java/org/opendatakit/aggregate/client/permissions/AccessConfigurationSheet.ui.xml, src/main/java/org/opendatakit/common/security/server/SecurityServiceUtil.java
Closes #336
First commit: `Fix user adding textbox to prevent Google Accounts`
Manually tried (and failed) to create new google account credentials.
This is the smallest possible change, which only involves client changes. Changing server side code felt too difficult and risky.
- Users should expect to be unable to create google account credentials.
- Since no server side code has been changed, existing google account credentials should work (not verified)
Also, during installation, we should suggest users to either migrate accounts to normal ODK type accounts or remove their google account credentials.
Nope.
I bet! I'll create issues once the release is ready.
=> Issue 336 remove google account credentials

src/main/java/org/opendatakit/aggregate/client/permissions/AccessConfigurationSheet.java, src/main/java/org/opendatakit/aggregate/servlet/ResetUsersAndPermissionsServlet.java
Closes #336
Manually tested:
- Edit a username and enter an email
- Upload a CSV with an ODK type account with an email as username
- Upload a CSV with a Google type account
None of this works and an error message is shown explaining why to the user
N/A
Users should expect to no longer be able to maintain their existing Google accounts, although this shouldn't be very common since they were deprecated some time ago and they should have migrated to ODK accounts before Aggregate v2.0
Nope.
Yes, we should add a warning in the installer too.
=> Issue 336 remove google account support

src/main/java/org/opendatakit/aggregate/query/submission/QueryBase.java, src/main/java/org/opendatakit/aggregate/query/submission/QueryByUIFilterGroup.java
Closes #359, and #360
Try to filter submissions by submission date or "date marked as complete" metadata fields and verify it works
This is the narrowest solution I could thin of.
Nope.
No.
No.
=> Issue 359 filter metadata date marked as complete

src/main/java/org/opendatakit/aggregate/AggregateUI.gwt.xml, src/main/java/org/opendatakit/aggregate/client/popups/ConfirmPurgeUpToDatePopup.java, src/main/java/org/opendatakit/aggregate/client/table/ExportTable.java, src/main/java/org/opendatakit/aggregate/client/table/PublishTable.java, src/main/java/org/opendatakit/aggregate/client/widgets/PurgeButton.java, src/main/java/org/opendatakit/common/utils/GwtShims.java, src/main/java/org/opendatakit/common/utils/Utils.gwt.xml
Closes #370
- Manually checked correct date formats on the purge dialogs (submissions and publishers)
- Manually checked correct dateTime formats on the export and publisher tables
The *best* solution would be that GWT emulates `java.time` and we can reuse JRTemporal on the client but, unfortunately, it doesn't.
I've reproduced the same formats on a new GwtShims class, which is reused across the web UI.
Nope.
Nope.
Yes, along with other changes in v2.0
=> Issue 370 fix date format on dialogs

src/main/java/org/opendatakit/aggregate/query/submission/QueryByUIFilterGroup.java
Closes #373
Manually tested following the instructions on #373.
This PR improves the detection of temporal fields of forms uploaded before upgrading to v2.0
- They can lack their FormElementModel
- They can be metadata fields
- They can have a FormElementModel without child elements
Nope.
Yes. The instructions to reproduce the scenario are attached to #373
Nope.
=> Issue 373 Temporal filters after upgrading to v2.0

src/main/java/org/opendatakit/aggregate/format/element/BasicElementFormatter.java, src/test/java/org/opendatakit/aggregate/format/element/BasicElementFormatterTest.java
Closes #380
Added new test cases to verify that we can format geopoints that lack altutide or accuracy components
This is the smallest change I could come up that takes into account that a geopoint value, and its lat, lon, alt, and acc can be `null`.
Nope.
No. Any form with geopoints will do.
No.
=> Issue 380 Fix geopoint formatting when it lacks alt or acc components

src/main/java/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java, src/main/java/org/opendatakit/aggregate/servlet/FragmentedCsvServlet.java, src/main/java/org/opendatakit/aggregate/submission/type/jr/JRTemporalUtils.java, src/main/java/org/opendatakit/aggregate/util/DateTimeUtils.java, src/main/java/org/opendatakit/common/persistence/engine/EngineUtils.java, src/test/java/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosaTest.java, src/test/java/org/opendatakit/aggregate/submission/type/jr/JRTemporalUtilsTest.java
Closes #379
- Pushed a form with the `-fsb` flag to enforce parsing the blank form again
- Added new unit tests to verify the change and prevent regression
This is a small change to consider another case where incoming datetime's offset data string should be fixed to a standard iso8601 format.
Nope.
No.
No.
=> Issue 379 Fix bug in fixOffset method

installer/project/components/params.xml
Closes #368
Manually run the installer
Nope.
Nope.
Yes, like the other v2 prs
=> Issue 368 add upgrade from v1 warning to the installer

src/main/java/org/opendatakit/aggregate/HttpUtils.java, src/main/java/org/opendatakit/aggregate/servlet/AggregateHtmlServlet.java, src/main/java/org/opendatakit/aggregate/servlet/ClearSessionThenLoginServlet.java, src/main/java/org/opendatakit/aggregate/servlet/MultimodeLoginPageServlet.java, src/main/java/org/opendatakit/common/security/server/SecurityServiceImpl.java
Closes #391
Build on top of #390. See just the last commit
To check that this works, you have to verify that logging in and changing the administrator password works as expected.
I've verified it in the local dev server (gradle), with the local cloudconfig stack.
I'm testing it on DO as well. Will update this when I get the results.
This bug is related to how Swing builds redirection URLs with the `HttpServletResponse.sendRedirect()` method.
When Aggregate is running behind a proxy, the URLs Swing generates have the wrong domain, wrong port, or they can lack the port number, which won't work.
After searching for uses of `sendRedirect()` in the code, I've seen a few of them that could be replaced by manually setting the redirection response:
- set the status to 302
- set a `Location` …
=> Issue 391 fix http 302 redirects behind proxy

cloud-config/assets/cloud-config.yml, cloud-config/digital-ocean/README.md, cloud-config/virtualbox/cloud-config.tpl.yml
This PR fixes the Cloud-Config scripts to use proper urls and names for the Aggregate CLI v1.0.3
- After the change from `aggregate-updater` to `aggregate-cli`, there were still some spots in the CloudConfig stacks pending to be changed
Run the stack on VirtualBox and DO and verify that it runs the installer CLI op.
=> Fix Cloud-Config scripts

cloud-config/assets/cloud-config.yml, cloud-config/virtualbox/cloud-config.tpl.yml, docs/aggregate-config.md, installer/project/files/conf/mysql/odk-settings.xml, installer/project/files/conf/postgresql/odk-settings.xml, installer/project/files/conf/sqlserver/odk-settings.xml, src/main/java/org/opendatakit/aggregate/servlet/AggregateHtmlServlet.java, src/main/java/org/opendatakit/aggregate/servlet/MultimodeLoginPageServlet.java, src/main/java/org/opendatakit/common/security/Realm.java, src/main/resources/odk-settings.xml.example, src/main/resources/security.properties.example
Closes #401
Also fixes the Cloud-Config stack to install only releases (remove the `--include-pre-releases` flag from the aggregate-cli install command)
Run locally with the Cloud-Config stack for VirtualBox
Upload a [Simple Form](https://github.com/opendatakit/briefcase/blob/master/test/resources/org/opendatakit/briefcase/export/simple-form.xml), a [Media Files](https://github.com/opendatakit/briefcase/blob/master/test/resources/org/opendatakit/briefcase/export/media-files.xml) form, and [Birds](https://github.com/opendatakit/sample-forms/archive/master.zip)
Get the forms with my android device, fill some subs and send them
Pull the forms with Briefcase and check the files in my storage directory
I've also tried it in DigitalOcean using the latest aggregate-cli and emulating a release in …
=> Issue 401 check hostnames conditionally

cloud-config/assets/cloud-config.yml
Confirmed this works with clean install on DO. Also confirmed HTTPS certs are installed.
Narrowest fix possible. 
Yes. I am still getting infinite redirects even after using aggregate-cli to install a custom war. Not sure where the problem is, but my recommendation is that we get as close to a stock install as possible. So I'd recommend... 
1. Merge this change.
1. Publish master as a temporary v2.0.0 pre-release WAR on GitHub
1. Copy this PRs [cloud-config](https://raw.githubusercontent.com/opendatakit/aggregate/bf0d82d7fde05d4bc1417f1bf77a2958db29b901/cloud-config/assets/cloud-config.yml) into DO.
1. Edit the config so aggregate-cli gets pre-releases (add `-ip`)
1. Confirm that cloud-init-output is clean
1. Run certbot to get HTTPS working
1. Confirm if page loads with no redirects
No.
=> Fix sed error that breaks installs

installer/project/components/configure_war.xml, installer/project/components/params.xml, installer/project/files/conf/mysql/odk-settings.xml, installer/project/files/conf/postgresql/odk-settings.xml, installer/project/files/conf/sqlserver/odk-settings.xml
Closes #420, and #429
Build the installer, check the files it deploys, and deploy in local tomcat
Build the installer (linux-x64) and run it, then deploy the resulting WAR into a local Tomcat. Verify that Aggregate launches without changing anything.
The changes are conforming to any other task in the installer (set values in conf files, etc.)
This PR adds some required adaptations from v1.x to v2.x into the installer
In v1.x, the `odk-settings.xml` for each platform comes with a hard-coded driver classname, which deviates from the same file in the code repo, which uses whatever value is defined in the jdbc.driverClassName` props key in `jdbc.properties`
In v2.x, we have made an effort to normalize all the different configuration assets, and we changed the `odk-settings.xml` that the …
=> Issue 420 fix installer conf file assets

src/main/java/org/opendatakit/aggregate/servlet/ClearSessionThenLoginServlet.java
Closes #419 
Run Aggregate in a local Tomcat both as ROOT and non-ROOT webapp, having configured a hostname and disabled the hostnames check.
In master, the login of the non-ROOT webapp won't work, and this PR solves that.
Also tested that this PR doesn't break the Cloud-Config stack by running it locally and verifying that the login still works.
This PR solves a regression bug introduced in v2.0.0. The change is to restore the original redirection code.
Nope.
No.
No.
=> Revert to previous code that had the webapp's path into account

src/main/java/org/opendatakit/aggregate/servlet/FormUploadServlet.java, src/main/java/org/opendatakit/aggregate/servlet/ResetUsersAndPermissionsServlet.java, src/main/java/org/opendatakit/aggregate/servlet/SubmissionServlet.java
Closes #409
Verify in Aggregate:
- Uploading forms works
- Manually uploading a submission works
- Changing user password and granted permissions works
Verify using Briefcase:
- Pushing a form with submissions works
HTTP 204 responses should not have a `Location` header. 
Nope.
No.
No.
=> Issue 409 remove Location header from 204 HTTP responses

build.gradle, src/main/java/org/opendatakit/aggregate/client/popups/PublishPopup.java
Closes #208, #209, #210
Manually tried all field combinations in both publishers in the dev server.
No other approaches were considered. It's the narrowest change I could come up with that provides basic form validation.
An alternative would be to disable the button if the form is not valid. I don't have a strong opinion about this approach.
Common publisher form changes:
- Alerts will be shown when no type of publisher or kind of upload (all, new, existing) is selected
There is really no way to test this without tampering with the form, although validating forms is always a good idea. These validations will be handy in case we change the form and we open the option of not selecting an option on those selects.
Changes to the Google Spreasheet publisher form:
- Users should expect a new …
=> Issue 210 validate publisher form

src/main/java/org/opendatakit/common/security/server/SecurityServiceImpl.java
Closes #440 
Launches as non-ROOT webapp in a local tomcat server and changed the password while inspecting the network tab using Chrome's developer console.
This fixes the issue like in https://github.com/opendatakit/aggregate/commit/048410e8ba18900e642d18db6aa60acf9fa184e2
Nope.
No.
No.
=> Issue 440 Fix change password url generation

installer/gae.zip
This PR updates the AppEngine Uploaded app JAR that the installer uses to deploy Aggregate to AppEngine.
The new uploader includes https://github.com/opendatakit/aggregate-components/pull/5 to avoid problems due to the deprecation of the AppEngine Backends API by Google.
=> Update AppEngine uploader app jar

README.md, docker/docker-entrypoint.sh, docs/build-and-run-a-docker-image.md
*I’m working on deploying an Aggregate 2.0 instance to Kubernetes in the cleanest possible way, and documenting my progress in [these lab notes](https://brettneese.xyz/tagged/migrating-odk-to-k8s). The latest [post](https://brettneese.xyz/lab-notes-migrating-odk-aggregate-from-fargate-to-azure-kubernetes-services-part-2) describes the motivation behind this change in even more detail.*
This PR allows optionally passing files via Docker volumes into a `/etc/config` directory in the Docker image, which gets symlinked via changes to `docker-entrypoint.sh` to the proper place in Aggregate's config directory. This allows complete control over the files (for instance, to use a different DB engine than pgsql.) Currently this covers:
- `${AGGREGATE_CONF_DIR}/odk-settings.xml`
- …
=> Allow mounting configuration files via Docker Volumes

installer/project/components/params.xml
Closes #452
Ensure that the installer sets the hostname in output conf files
- Previously, we had a post-installation action that would copy the value of raw_hostname to hostname and perform transformations conditionally if the user was using GAE
- When we removed support for GAE, we broke this by removing all the post-installation actions related to the hostname variable
- In this commit, raw_hostname becomes hostname, fixing the issue
- This commit also adds a couple of hints to help the user fill in a value.
- Users are reminded that the hostname must match their SSL certificate.
Screenshot of the `Apache Tomcat Port Configuration` screen when `no SSL` is selected:
Screenshot of the `Apache Tomcat Port Configuration` screen when `SSL` is selected:
Build the installer, run it and verify …
=> Issue 452 The installer is not configuring the hostname correctly

src/main/java/org/opendatakit/aggregate/client/LayoutUtils.java, src/main/java/org/opendatakit/aggregate/client/preferences/PreferenceService.java, src/main/java/org/opendatakit/aggregate/client/preferences/PreferenceServiceAsync.java, src/main/java/org/opendatakit/aggregate/server/PreferenceServiceImpl.java, src/main/java/org/opendatakit/aggregate/servlet/AggregateHtmlServlet.java
Closes #459
I've used Chrome's inspector for all these tests with the "Disable cache" from the network tab enabled.
**Version note blocking issues**
- Start Aggregate in `localhost` and verify that I get the "you're up to date" note. 
- Restart Aggregate, disable the network connection and verify that I get the "version check failed" note.
**Google maps JS blocking issues**
- Start Aggregate and verify with the inspector that the script gets eventually loaded.
- Restart Aggregate, disable the network connection and verify that I get an error but the page still loads.
First I tried to modify the client's JSNI implementation in `LayoutUtils.java` to handle errors related to the requests to GitHub's API, but I got to very complicated half-solutions due to conflicts between the blocking …
=> Issue 459 avoid page load blocks

src/main/java/org/opendatakit/aggregate/servlet/FormUploadServlet.java, src/main/java/org/opendatakit/aggregate/servlet/ResetUsersAndPermissionsServlet.java, src/main/java/org/opendatakit/aggregate/servlet/SubmissionServlet.java
Closes #455
Run Aggregate and use curl to verify that the `Location` header is in the response of the HEAD. I verified the two that can be accessed without auth and expect that the third will work because it has been changed the same way.
```
$ curl -XHEAD -I http://localhost:8080/formUpload
HTTP/1.1 204 No Content
Date: mié, 24 abr 2019 08:26:05 GMT
X-OpenRosa-Version: 1.0
X-OpenRosa-Accept-Content-Length: 10485760
Location: http://localhost:8080/formUpload
Server: Jetty(9.2.22.v20170606)
$ curl -XHEAD -I http://localhost:8080/submission
HTTP/1.1 204 No Content
Date: mié, 24 abr 2019 08:26:11 GMT
X-OpenRosa-Version: 1.0
X-OpenRosa-Accept-Content-Length: 10485760
Location: http://localhost:8080/submission
Server: Jetty(9.2.22.v20170606)
```
This is the old code that's running in 1.7 …
=> Issue #455 Restore the Location header in HEAD pre-flight responses

buildSrc/src/main/groovy/org/opendatakit/aggregate/gradle/Util.groovy, gradle.properties.example, installer.gradle, installer/project/buildWar.xml
Now the Gradle task will automate the generation of all the installer if the installBuilderHome variable is set.
- The installers are generated following the filename templates we require in our releases.
- The task will only work in Linux and macOS hosts.
- The installers are built and zipped by the task, and they can be found at `build/installers`
The way to run the task hasn't changed: 
`./gradlew clean build installerBuild -xtest -PwarMode=installer`
=> Improve the installerBuild task to produce the installers

src/main/java/org/opendatakit/aggregate/externalservice/JsonServer.java
When a server responds with another 2XX code, such as 201 the server treats this as an error. This accepts any 2XX response.
I used the number 300 instead of SC_MULTIPLE_CHOICES as that constant's name doesn't signify the start of the non success range.
We'll be deploying this shortly.
Any 2XX code is a success code.
No.
No
=> allow any 2XX status code from an external JSON server

cloud-config/aws/cloud-config.yml, cloud-config/azure/cloud-config.yml, cloud-config/digital-ocean/cloud-config.yml, cloud-config/google-cloud/startup-script.sh, cloud-config/virtualbox/cloud-config.tpl.yml
We have renamed opendatakit/aggregate to getodk/aggregate. Web browsers follow the redirect by default, but curl doesn't unless you add `-L`.
=> Instruct curl to follow redirects

README.md, cloud-config/aws/cloud-config.yml, cloud-config/azure/cloud-config.yml, cloud-config/digital-ocean/cloud-config.yml, cloud-config/google-cloud/startup-script.sh, cloud-config/virtualbox/cloud-config.tpl.yml, packer/ansible/roles/unattended-upgrades/tasks/main.yml
* Ensure postgres can chdir or you get a "could not change directory to "/root": Permission denied" error. See https://stackoverflow.com/questions/35782366 for alternatives.
* Do not run unattended-upgrades because it's very slow (especially on DO) and blocks the rest of the install. The OS will run it eventually.
The PR itself doesn't require a new release (which is great). And it's relatively safe because if installs fail, we'll likely get support requests and we can respond then.
I did a search for "unattended-upgrade" and "postgres -c" to make sure I didn't miss anything.
=> Skip slow unattended-upgrades install, ensure postgres can chdir
