getodk/aggregate

README.md

Fixed: https://github.com/opendatakit/opendatakit/issues/1294

Updated: ODK Forum & Slack Links

---

build.gradle

This solves https://github.com/opendatakit/aggregate/issues/119

Update JavaRosa dependency to version 2.6.0

---

docs/intellij_setup.md

The change at the bottom probably has to do with a missing newline.

Minor edit

---

README.md
build.gradle
docs/intellij_setup.md

Issue 132 gretty integration

---

src/main/java/org/opendatakit/aggregate/client/popups/VisualizationPopup.java

Closes #156 
Follow the instructions in #156 and verify that works as expected
This is a simple change on the options to instantiate the map
Being this so simple, I can only think that if this wasn't already in the code, maybe there was an important enough reason to not do it in the first place...
Nope.

Enable mouse dragging to pan the map and mouse wheel for zoom

---

build.gradle
buildSrc/src/main/groovy/org/opendatakit/aggregate/gradle/Util.groovy
src/main/java/org/opendatakit/aggregate/client/PreferencesSubTab.java
src/main/java/org/opendatakit/aggregate/client/popups/HelpBookPopup.java
src/main/resources/security.properties

**Adds artifact versioning system from Briefcase**
Now WAR files are versioned following the same scheme as in Briefcase.
**Adds a notice about the running version inside the HelpBoopPopup**
The version is written into a `BuildConfig` class by Gradle and it's printed inside the Help popup

Support versioning like in Briefcase

---

build.gradle
config/checkstyle/checkstyle.xml

Closes #171
This is a safe, automatic code reformat performed by IntelliJ. Nevertheless, I've checked that the project compiles and runs.
It is what makes sense since we use IntelliJ as the official IDE for Aggregate
This should be a safe change because code formatting is done by the IDE automatically
N/A

Issue 171 code style normalization

---

.circleci/config.yml

Confirmed that the build produces reports and libs.
We use CircleCI and we need it on all our tools. This PR does not test the code, but that will come eventually. 
None.

Add CI support

---

.gitignore
build.gradle
src/test/java/org/opendatakit/aggregate/format/table/CsvFormatterWithFiltersTest.java

Closes #40 
Manual end-to-end test with collect and aggregate, using the attached form and resulting csv output. Added automated test cases to ensure no regressions
It may not be...up for debate whether introducing Mockito was really necessary or not here. We can debate whether subclassing custom mocks is more appropriate.
No risks.
Attached (although no necessarily needed)!

Test coverage for CSV export: no emitting "null" for no value (#40)

---

.circleci/config.yml
gradle/wrapper/gradle-wrapper.properties

Done to stay consistent with the other ODK projects

Upgrade gradle

---

build.gradle
installer/ear.zip
src/main/gae_ear/background/WEB-INF/appengine-web.xml
src/main/gae_ear/default/WEB-INF/appengine-web.xml

Closes #184 
Built, run and deployed in GAE
This PR just changes version numbers around
Apparently not, but full QA is advised.
Nope.
Nope.

Java8 runtime

---

src/main/java/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java

Closes #251
Upload the attached form, which uses the post method.
It's a straightforward change.
Nope.
[encrypted-form-post.txt](https://github.com/opendatakit/aggregate/files/2097832/encrypted-form-post.txt)
Nope.

Allow to upload submissions using the HTTP POST method

---

src/main/java/org/opendatakit/aggregate/client/table/PublishTable.java

Closes #269
Create a JSON server publisher and verify that there's a clickable link pointing to the server.
Create a google sheet publisher and verify that it works as before.
This is a straightforward change to generate an HTML link
Nope.
Nope.
Nope.

Issue 269 clickable link to json server

---

installer/README.md

Closes #275
This PR adds a note linking this repo with the Aggregate Components repo and some basic info about all the files and folders inside the `installer` directory.
We can expand on this next time we visit the installer to make some change.
There are no code changes.
N/A
N/A
N/A
N/A

Issue 275 Add basic README.md with info about the installer sources

---

src/main/java/org/opendatakit/aggregate/client/popups/ConfirmExportDeletePopup.java
src/main/java/org/opendatakit/aggregate/client/popups/ConfirmFormDeletePopup.java
src/main/java/org/opendatakit/aggregate/client/popups/ConfirmPublishDeletePopup.java
src/main/java/org/opendatakit/aggregate/client/popups/ConfirmPurgeUpToDatePopup.java
src/main/java/org/opendatakit/aggregate/client/popups/ConfirmUserDeletePopup.java
src/main/java/org/opendatakit/aggregate/client/popups/PurgeUpToDatePopup.java

Closes #273
Verified that the dialog works as expected:
Straightforward fix.
Nope.
Nope.
Nope.

Issue 273 Fix HTML generation for delete form dialog

---

README.md
docker-compose.gradle
docker.gradle
docs/README.md
docs/build-and-run-a-docker-image.md
docs/build-and-run-a-virtual-machine.md
docs/build-and-run-with-docker-compose.md
docs/build-the-installer-app.md

Closes #285
This PR doesn't change Aggregate's behavior
This PR improves the README files and the docs.
Browsed the new links.
N/A
Nope.
Nope.
Nope.

Issue 285 improve readme with contents of docs

---

README.md
docs/README.md

Addresses #289
Visual inspection

Removing app name because it is clear from context

---

src/main/java/org/opendatakit/aggregate/task/tomcat/WatchdogImpl.java

Replace System.out.println by logger output in Watchdog (closes #140)

---

docs/build-and-run-a-docker-image.md

As encountered in issue #314, not following the correct dev environment setup in the master README will result in unexpected and confusing errors. The new additions are what I believe are the minimum working steps for a successful Docker build under Ubuntu 16.04. Windows and Mac environments/users may require additional steps/caveats.
#314
As documented in #314, I have successfully built a Docker image.
Updating the docs should be sufficient to remind other builders of Docker images of the required steps for a successful build.
No, it's only a change to docs.
No
No, the ODK docs point to the Docker build README I'm proposing to update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

 Clarify requirements for Docker build 

---

src/main/java/org/opendatakit/aggregate/client/AggregateUI.java
src/main/java/org/opendatakit/aggregate/client/ExportSubTab.java
src/main/java/org/opendatakit/aggregate/client/FiltersDataPanel.java
src/main/java/org/opendatakit/aggregate/client/FormsSubTab.java
src/main/java/org/opendatakit/aggregate/client/LayoutUtils.java
src/main/java/org/opendatakit/aggregate/client/PermissionsSubTab.java
src/main/java/org/opendatakit/aggregate/client/PreferencesSubTab.java
src/main/java/org/opendatakit/aggregate/client/PublishSubTab.java
src/main/java/org/opendatakit/aggregate/client/SubmissionAdminSubTab.java

Closes #330 
This PR adds a background to the help layer to hide the version note

Small UI improvements to the version note

---

src/main/java/org/opendatakit/common/security/server/SecurityServiceUtil.java

Closes #351
Aggregate now starts without errors
This PR repeats the same fix applied in another PR in 2 places that were missed by that PR.
Nope.
Nope.
Nope.

Issue 351 Fix badGrants processing code

---

src/main/java/org/opendatakit/aggregate/constants/common/UIConsts.java
src/main/java/org/opendatakit/common/security/Realm.java

Closes #355
I haven't done any verification other than compiling Aggregate. The changes are pretty narrow and safe.
N/A
None.
Nope.
No.

Issue 355 hardcoded version

---

src/main/java/org/opendatakit/aggregate/client/popups/ConfirmPurgePopup.java

Closes #387
Run Aggregate and verify the date format is OK when purging submissions.
Super narrow fix
Nope.
No.
No.

Issue 387 Fix date format in JS confirmation dialog

---

README.md

Addresses #396
This is totally unverified, but I believe it to be correct 😂

Consolidate DB creation in readme to match project

---

docs/build-and-run-a-docker-image.md
docs/database-configurations.md
gradle.properties.example
src/main/resources/jdbc.properties.example

* Built a VM with VirtualBox 6, switched to bridged mode, got a submission working.
* Did not test the Docker documentation changes, but those are docs and should be safe.
As narrow as it gets. Can probably wait until after release.
packer breaks on old versions of Virtualbox. Existing users shouldn't be affected since their packer version is set.
No.
No.

Virtualbox 6 fix

---

cloud-config/assets/cloud-config.yml
cloud-config/virtualbox/cloud-config.tpl.yml

Closes #411
* Checked to make sure this repo and the CLI repo don't call tar, vim, or tree.
* Checked on VPS to make sure `curl -s` doesn't show progress bar

v2.0.0 release tweaks

---

README.md
cloud-config/assets/cloud-config.yml
cloud-config/virtualbox/cloud-config.tpl.yml
db/postgresql/image/init.sh
db/test/postgresql/init.sql
docker-compose/initdb/init.sh
docs/build-and-run-a-docker-image.md
docs/database-configurations.md
packer/ansible/roles/aggregate/files/init.sql

Closes #410
- Tested the Cloud-Config stack (only virtualbox, since that part is the same in the DO stack)
- Tested the docker compose build
- Tested the packer VM
Other changes (docs) checked visually.
This is important to have smoother database management. Dump files drop tables, which can produce errors if ownership is not set correctly.
No.
No.
No.

Issue 410 Set db schema ownership

---

src/main/java/org/opendatakit/aggregate/servlet/BinaryDataServlet.java
src/main/java/org/opendatakit/aggregate/servlet/GetUsersAndPermissionsServlet.java

Fixes: https://forum.opendatakit.org/t/invalid-character-in-last-modified-header-tomcat8-with-odk-aggregate/9162
Currently cherry-picking the change to the release we are using and building a new jar.
Bug fix
None
No
No

fix bad caching headers

---

build.gradle

Revert accidental change on gretty configuration.

Revert gretty hostname

---

README.md
build.gradle
docker.gradle
docs/build-and-run-a-docker-image.md

_I'm working on deploying an Aggregate 2.0 instance to Kubernetes in the cleanest possible way, and documenting my process [here](https://www.brettneese.xyz/lab-notes-migrating-odk-aggregate-from-fargate-to-azure-kubernetes-service)._ 
This PR enables the ability to run the Gradle build commands for Docker without manually copying the `*.example` config files. I noticed that `docker.gradle` automatically overrides any settings in those files, anyway in the `dockerPrepare` build script so it made sense to have the build script just rename those files. Now you can build without manual work.
The only hacky thing I had to do was check the build commands sent to Gradle in the `checkConf` task against whether this was a build for Docker, which may be less than ideal, but seemed better than …

Docker config improvements

---

build.gradle

This PR bumps JR to avoid errors coming from new JR features that Aggregate might have trouble parsing when uploading new blank forms.
Compile Aggregate and run local dev server
N/A
No. Aggregate ignores new JR features that are not representable in the web UI.
No.
No.

Bump JR to 2.14.0

---

src/main/java/org/opendatakit/aggregate/client/LayoutUtils.java
src/main/java/org/opendatakit/aggregate/client/preferences/PreferenceService.java
src/main/java/org/opendatakit/aggregate/client/preferences/PreferenceServiceAsync.java
src/main/java/org/opendatakit/aggregate/server/PreferenceServiceImpl.java
src/main/java/org/opendatakit/aggregate/servlet/AggregateHtmlServlet.java

Closes #461
Run the same verification as in #460 
N/A
N/A
N/A
N/A

Issue 461 backport 460

---

.circleci/config.yml
db/test/mysql/init.sql
docs/database-configurations.md

Closes #464
Ran it on my CircleCI account branch and ensured the tests ran. I was able to verify that the artifacts showed up in the CI UI.
It was the fastest way to get it working. I bet we could reduce the duplication and maybe use one container, but I'll leave that as an exercise for the next person.
I've reverted back to Postgres 9.4 and combined the config so maybe that will cause a problem.

Enable tests on MySQL CI image

---

build.gradle

Quick patch to update to the latest available JR.

Bump JR to v2.17.0

---

src/main/java/org/opendatakit/aggregate/externalservice/JsonServer.java

allow any 2XX status code from an external JSON server

---

CODE_OF_CONDUCT.md

Closes #198 
I manually viewed and confirmed that the CODE_OF_CONDUCT.md file has been added and contains the required content.
It follows the recommended course of action in issue #198 
No.
No.
No.

Add CODE_OF_CONDUCT.md file. Closes #198

---

src/main/java/org/opendatakit/aggregate/constants/ErrorConsts.java
src/main/java/org/opendatakit/aggregate/servlet/FormUploadServlet.java

Closes #244 
I performed manual testing.
It follows the recommended course of action in issue #244 
No.
No.
Yes. https://github.com/getodk/docs/issues/1236

Improve form version conflict error message. Closes #244

---

README.md

I think it's important that people coming to this repository know not to expect active development. I'll be working on a parallel documentation update.

Update README to indicate status
